// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"database/sql"
	"time"
)

type File struct {
	ID           int64
	FilePath     string
	DiscoveredAt time.Time
	Status       sql.NullString
	Error        sql.NullString
}

type UploadJob struct {
	ID         int64
	FileID     int64
	HostName   string
	Status     sql.NullString
	RetryCount sql.NullInt64
	LastError  sql.NullString
	EmbedID    sql.NullString
	UpdatedAt  sql.NullTime
}
