// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package sqlc

import (
	"context"
	"database/sql"
)

const addFile = `-- name: AddFile :exec
INSERT INTO files (file_path) VALUES (?)
`

func (q *Queries) AddFile(ctx context.Context, filePath string) error {
	_, err := q.db.ExecContext(ctx, addFile, filePath)
	return err
}

const addUpload = `-- name: AddUpload :exec
INSERT INTO upload_jobs (file_id, host_name, status, last_error, slug_id) VALUES (?, ?, ?, ?, ?)
`

type AddUploadParams struct {
	FileID    int64
	HostName  string
	Status    string
	LastError sql.NullString
	SlugID    sql.NullString
}

func (q *Queries) AddUpload(ctx context.Context, arg AddUploadParams) error {
	_, err := q.db.ExecContext(ctx, addUpload,
		arg.FileID,
		arg.HostName,
		arg.Status,
		arg.LastError,
		arg.SlugID,
	)
	return err
}

const completeUpload = `-- name: CompleteUpload :exec
UPDATE upload_jobs SET status = "DONE", slug_id = ? WHERE id = ?
`

type CompleteUploadParams struct {
	SlugID sql.NullString
	ID     int64
}

func (q *Queries) CompleteUpload(ctx context.Context, arg CompleteUploadParams) error {
	_, err := q.db.ExecContext(ctx, completeUpload, arg.SlugID, arg.ID)
	return err
}

const failUpload = `-- name: FailUpload :exec
UPDATE upload_jobs SET status = "FAILED", last_error = ? WHERE id = ?
`

type FailUploadParams struct {
	LastError sql.NullString
	ID        int64
}

func (q *Queries) FailUpload(ctx context.Context, arg FailUploadParams) error {
	_, err := q.db.ExecContext(ctx, failUpload, arg.LastError, arg.ID)
	return err
}

const findFileByPath = `-- name: FindFileByPath :one
SELECT id, file_path, discovered_at, status, error FROM files WHERE file_path=? LIMIT 1
`

func (q *Queries) FindFileByPath(ctx context.Context, filePath string) (File, error) {
	row := q.db.QueryRowContext(ctx, findFileByPath, filePath)
	var i File
	err := row.Scan(
		&i.ID,
		&i.FilePath,
		&i.DiscoveredAt,
		&i.Status,
		&i.Error,
	)
	return i, err
}

const getFileUploads = `-- name: GetFileUploads :many
SELECT id, file_id, host_name, status, retry_count, last_error, slug_id FROM upload_jobs WHERE file_id=?
`

func (q *Queries) GetFileUploads(ctx context.Context, fileID int64) ([]UploadJob, error) {
	rows, err := q.db.QueryContext(ctx, getFileUploads, fileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UploadJob
	for rows.Next() {
		var i UploadJob
		if err := rows.Scan(
			&i.ID,
			&i.FileID,
			&i.HostName,
			&i.Status,
			&i.RetryCount,
			&i.LastError,
			&i.SlugID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPendingFile = `-- name: GetPendingFile :many
SELECT id, file_path, discovered_at, status, error FROM files WHERE status = 'PENDING'
ORDER BY id LIMIT ? OFFSET ?
`

type GetPendingFileParams struct {
	Limit  int64
	Offset int64
}

func (q *Queries) GetPendingFile(ctx context.Context, arg GetPendingFileParams) ([]File, error) {
	rows, err := q.db.QueryContext(ctx, getPendingFile, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []File
	for rows.Next() {
		var i File
		if err := rows.Scan(
			&i.ID,
			&i.FilePath,
			&i.DiscoveredAt,
			&i.Status,
			&i.Error,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateFileStatus = `-- name: UpdateFileStatus :exec
UPDATE files SET status = ?, error = ? WHERE id = ?
`

type UpdateFileStatusParams struct {
	Status string
	Error  sql.NullString
	ID     int64
}

func (q *Queries) UpdateFileStatus(ctx context.Context, arg UpdateFileStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateFileStatus, arg.Status, arg.Error, arg.ID)
	return err
}
