// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package sqlc

import (
	"context"
	"database/sql"
)

const getFileUploads = `-- name: GetFileUploads :many
SELECT id, file_id, host_name, status, retry_count, last_error, slug FROM upload_jobs WHERE file_id=?
`

func (q *Queries) GetFileUploads(ctx context.Context, fileID int64) ([]UploadJob, error) {
	rows, err := q.db.QueryContext(ctx, getFileUploads, fileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UploadJob
	for rows.Next() {
		var i UploadJob
		if err := rows.Scan(
			&i.ID,
			&i.FileID,
			&i.HostName,
			&i.Status,
			&i.RetryCount,
			&i.LastError,
			&i.Slug,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFilesByStatus = `-- name: GetFilesByStatus :many
SELECT id, file_path, discovered_at, archived, status FROM files WHERE status = ? ORDER BY id
`

func (q *Queries) GetFilesByStatus(ctx context.Context, status string) ([]File, error) {
	rows, err := q.db.QueryContext(ctx, getFilesByStatus, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []File
	for rows.Next() {
		var i File
		if err := rows.Scan(
			&i.ID,
			&i.FilePath,
			&i.DiscoveredAt,
			&i.Archived,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUnArchivedFiles = `-- name: GetUnArchivedFiles :many
SELECT id, file_path, discovered_at, archived, status FROM files WHERE archived = FALSE
`

func (q *Queries) GetUnArchivedFiles(ctx context.Context) ([]File, error) {
	rows, err := q.db.QueryContext(ctx, getUnArchivedFiles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []File
	for rows.Next() {
		var i File
		if err := rows.Scan(
			&i.ID,
			&i.FilePath,
			&i.DiscoveredAt,
			&i.Archived,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertFile = `-- name: InsertFile :exec
INSERT OR IGNORE INTO files (file_path, status) VALUES (?, 'pending')
`

func (q *Queries) InsertFile(ctx context.Context, filePath string) error {
	_, err := q.db.ExecContext(ctx, insertFile, filePath)
	return err
}

const resetProcessingStatuses = `-- name: ResetProcessingStatuses :exec
UPDATE files SET status = 'pending' WHERE status = 'processing'
`

func (q *Queries) ResetProcessingStatuses(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, resetProcessingStatuses)
	return err
}

const updateFileStatus = `-- name: UpdateFileStatus :exec
UPDATE files SET status = ? WHERE file_path = ?
`

type UpdateFileStatusParams struct {
	Status   string
	FilePath string
}

func (q *Queries) UpdateFileStatus(ctx context.Context, arg UpdateFileStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateFileStatus, arg.Status, arg.FilePath)
	return err
}

const upsertFile = `-- name: UpsertFile :exec
INSERT INTO files (file_path, status, archived) VALUES (?, ?, ?) 
ON CONFLICT (file_path) 
DO UPDATE SET 
    status = COALESCE(excluded.status, status),
    archived = COALESCE(excluded.archived, archived)
`

type UpsertFileParams struct {
	FilePath string
	Status   string
	Archived bool
}

func (q *Queries) UpsertFile(ctx context.Context, arg UpsertFileParams) error {
	_, err := q.db.ExecContext(ctx, upsertFile, arg.FilePath, arg.Status, arg.Archived)
	return err
}

const upsertUpload = `-- name: UpsertUpload :exec
INSERT INTO upload_jobs (file_id, host_name, status, slug, last_error)
VALUES (?, ?, ?, ?, ?)
ON CONFLICT (file_id, host_name)
DO UPDATE SET
    status      = COALESCE(excluded.status, status),
    slug        = COALESCE(excluded.slug, slug),
    last_error  = COALESCE(excluded.last_error, last_error),
    retry_count = retry_count + 1
`

type UpsertUploadParams struct {
	FileID    int64
	HostName  string
	Status    string
	Slug      sql.NullString
	LastError sql.NullString
}

func (q *Queries) UpsertUpload(ctx context.Context, arg UpsertUploadParams) error {
	_, err := q.db.ExecContext(ctx, upsertUpload,
		arg.FileID,
		arg.HostName,
		arg.Status,
		arg.Slug,
		arg.LastError,
	)
	return err
}
